config/routes.rb
Tests::Application.routes.draw do
  
	namespace :admin do
   resources :articles
  end
	
	get "login" => "sessions#new", :as => "login"
  resources :sessions
	get "log_out" => "sessions#destroy", :as => "log_out"

	get "sign_up" => "users#new", :as => "sign_up"
  resources :users  

  resources :articles, :comments
	root :to => "articles#index"
	
  get "say/hello"

  get "say/goodbye"

	match 'list_articles', :to => 'articles#index' 
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  #def hello
	#	@time = Time.now
	#	@hello = "Hello, World! via Controller"
  #end

  #def goodbye
  #end
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/say/goodbye.html.erb
<html>
	<head>
		<title>Training - RoR</title>
	</head>
	<body>
		<header>
			<h1>Good Bye !</h1>
		</header>
		<section>
			<p>
				GOOD BYE CONTENT HERE !
			</p>
		</section>
		<footer>
			<%= link_to "back", say_hello_path %>
			<%= a, b = 1, 2 %>
			<%= 1+2 %>
			<%= "CoW" + "BoW" %>
			<%= 2.hour.from_now %>
			<br />
			<hr />
			<% @files = Dir.glob('*') %>
			<ul>
			<% for file in @files %>
				<li>file name is: <%= file %></li>
			<% end %>
			</ul>
		</footer>
	</body>
</html>

app/views/say/hello.html.erb
<html>
	<head>
		<title>Training - RoR</title>
	</head>
	<body>
		<header>
			<h1>This is HEADING</h1>
			<span>-- tag line --</span>
		</header>
		<section>
			<p>
				<%= "Hello, World!" %> <br/>
				<%= @hello %> <br />
				<% [2,4,6,8,4,2,5].each do |number| %>
					<%= number %>
				<% end %><br />
			</p>
		</section>
		<footer>
			It is <%= @time%>
			<%= link_to "Bye!", say_goodbye_path %>
		</footer>
	</body>
</html>