config/routes.rb
Tests::Application.routes.draw do
  
	namespace :admin do
   resources :articles
  end
	
	get "login" => "sessions#new", :as => "login"
  resources :sessions
	get "log_out" => "sessions#destroy", :as => "log_out"

	get "sign_up" => "users#new", :as => "sign_up"
  resources :users  

  resources :articles, :comments
	root :to => "articles#index"
	
  get "say/hello"

  get "say/goodbye"

	match 'list_articles', :to => 'articles#index' 
end

app/models/article.rb
class Article < ActiveRecord::Base
  #attr_accessible :title, :body
	has_many :comments,  :dependent => :destroy # plural
	belongs_to :user
	#has_many :more_content,
  #         :class_name => "User" ,
  #           :foreign_key => "user_id" ,
  #           :conditions => "status = SELECT * FROM articles WHERE title LIKE '%Lip%'"
	#default_scope where("rating = 5")
	validates :title, :presence => { :message => "Article title is required" },
                    :uniqueness => true
	#validates_length_of :title, :in => 7..32, :allow_blank => false
	validates :body, :presence => { :message => "Article content is required"}
	#def self_article_content
		#"#{self.where("LENGTH(body) > 1")}"
  #end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::ApplicationController
  before_filter :require_admin_login
	protect_from_forgery
	
	#def new
  #  @article = Article.new
  #end
	
	def index
    @articles = Article.all
  end
	
	#def create
  #  @article = Articles.new
  #  redirect_to :controller => :users, :action => :index
  #end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :require_login, :only => [:new, :create, :edit, :update, :delete]
	
	def new
    @article = Article.new
  end
	
	def show
	  @article = Article.find_by_id(params[:id])
		@comments = @article.comments
		@comment = Comment.new
	end

  def edit
    @article = Article.find_by_id(params[:id])
  end
        
  def update
	 @article = Article.find_by_id(params[:id])
		if @article.update_attributes(params[:article])
			flash[:notice] = 'Article was successfully updated.'
			redirect_to articles_path
		else
			flash[:error] = 'Article was failed to update.'
			render :action => "update"
		end
	end

  def index
    @articles = Article.all
  end
        
  def create
    @article = Article.new(params[:article])
     if @article.save
      flash[:notice] = 'Article was successfully created.'
      #redirect_to :action => :index
      redirect_to articles_path
    else
      flash[:error] = 'Article was failed to create.'
      render :action => "new"
      #redirect_to new_article_path
    end
  end
        
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to :controller => :articles, :action => :index
		#flash[:notice] = 'Article was successfully updated.'
  end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/_comments.html.erb
<% comments.each do |comment| %>
  <%= comment.content %><br />
<% end %>

app/views/articles/edit.html.erb
<html>
	<head>
		<title>Edit</title>
	</head>
	<body>
		<header>
			<h1>Edit Page</h1>
		</header>
		<section>
      <section>
        <%= form_for @article do |f| %>  
          Title : <%= f.text_field :title %> 
          Content : <%= text_area :article, :body %>
          <%=f.submit :update%>
        <% end %>
      </section>
    </section>
		<footer>
      == &nbsp; Walden Global Service 2012==
		</footer>
	</body>
</html>

app/views/articles/index.html.erb
<html>
	<head>
		<title>Index</title>
	</head>
	<body>
		<header>
			<h1>Index Page</h1>
			<%= link_to "Admin", admin_articles_path %>
		</header>
		<section>
			<%= raw(welcome_text) %>
			<%= flash[:notice] %>
			<br />
			<%= raw(restriction_add) %>
			<% @articles.each do |a| %>
				<section>
					<h4><%= link_to a.title, article_path(a.id) %></h4>
					<p><%= a.body %></p>
					<br />
					<% if session[:user_id].to_i == a.user_id %>
					  
						<% if current_user %>
						  <%= link_to "Edit", edit_article_path(a.id) %>
							<%= link_to "Delete", article_path(a.id), :method => :delete, :confirm => "Are you sure?" %>
						<% end %>
					<% else %>
					<% end %>
					<br />
					<span>Writer : <%= a.user.first_name %></span>	
					<hr />
				</section>
			<% end %>
		</section>
		<footer>
      == &nbsp; Walden Global Service 2012==
		</footer>
	</body>
</html>

app/views/articles/new.html.erb
<html>
  <head>
    <title>New</title>
  </head>
  <body>
    <header>
      <h1>New Page</h1>
    </header>
    <section>
      <%= flash[:notice] %>
      <%= flash[:error] %>		
      <% #if @article.errors.any? %>
        <!-- <div id="errorExplanation">
          <h2>
            <%#= pluralize(@article.errors.count, "error") %> prohibited this user from being saved:
          </h2>
          <ul>
						
            <% #@article.errors.full_messages.each do |msg| %>
              <li><%#= msg %></li>
            <% #end %>
          </ul>
        </div> -->
      <% #end %>
      <%= form_for @article do |f| %>  
        Title : <%= f.text_field :title %> 
        Content : <%= text_area :article, :body %>
				<%= hidden_field :article, :user_id, :value => current_user.id %>
        <%=f.submit :new%>
      <% end %>
     </section>
    <footer>
      == &nbsp; Walden Global Service 2012==
    </footer>
  </body>
</html>

app/views/articles/show.html.erb
<section>
  <h4><%= @article.title %></h4>
  <p><%=  @article.body %></p>
  <section class="comment">
		<h6>Comments Sections</h6>
	  <!--This section is to show all comments that owned by the article  -->
    <div id="comments">
      <%= render :partial => "comments", :locals => {:comments => @comments}  %>
    </div><br /><br />
    <% unless(current_user.nil?)%>
      <%= form_for @comment, :url => comments_path, :remote => true do |f| %>
        <%= f.text_area :content %>
        <%= f.hidden_field :article_id, :value => @article.id %>
        <%= submit_tag "comment" %>
      <% end -%>
    <% end %>
	</section>
</section>